---
- name: Create the ansible user 
  ansible.builtin.user:
    name: "{{ ansible_user_name }}"
    group: "{{ ansible_group_name }}"
    shell: "{{ ansible_user_shell }}"
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_type: rsa
    home: /home/{{ ansible_user_name }}
  become: yes

- name: Create the tailscale user 
  ansible.builtin.user:
    name: "{{ tailscale_user_name }}"
    group: "{{ tailscale_group_name }}"
    shell: "{{ tailscale_user_shell }}"
    state: present
    home: /home/{{ tailscale_user_name }}
  become: yes

