---
- name: Check if tailscale repo exists
  ansible.builtin.shell: if [ -z "$(dnf repolist | grep tailscale)" ]; then echo "NOK"; else echo "OK"; fi
  register: tailscale_repo

- name:
  ansible.builtin.debug:
    msg: "{{ tailscale_repo }}"
