name: Ansible Config

run-name: Ansible Config Pipeline on ${{ inputs.Env }}

on:
  # Run the github action manually for the moment.
  workflow_dispatch:
  # Parameters of the pipeline
    inputs:
      Env:
        type: choice
        description: 'Environment'
        required: true
        options:
          - T1
          - PRD
      AvailabilityZone:
        type: choice
        description: 'Availability Zone'
        required: true
        options:
            - blue
            - red

jobs:
    ansible:
        runs-on: ubuntu-latest
        environment: ${{ inputs.Env }}
        steps:
          - uses: actions/checkout@v4

          - name: Set up ssh key
            run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/ansible_key
                chmod 600 ~/.ssh/ansible_key
                chmod 700 ~/.ssh
                ls -latr ~/.ssh/


          - uses: qetza/replacetokens-action@v1
            with:
              sources: 'ansible/inventory/envs/${{ inputs.Env }}/hosts.yml; ansible/infra.yml'
              variables: '[${{ toJson(secrets)}}, ${{ toJson(inputs)}}]'
              token-prefix: '#{'
              token-suffix: '}#'

          # - name: Set up Ansible
          #   uses: dawidd6/action-ansible-playbook@v5
          #   with:
          #     playbook: 'infra.yml'
          #     directory: 'ansible'
          #     inventory: 'inventory/envs/${{ inputs.Env }}/hosts.yml'
          #     configuration: 'ansible.cfg'

          - name: Ansible Playbook
            working-directory: ./ansible
            run: |
                ansible-playbook -i inventory/envs/${{ inputs.Env }}/hosts.yml infra.yml

        
          
