name: Test pipeline on ${{ github.event.inputs.Env }}

on:
  # Run the github action manually for the moment.
  workflow_dispatch:
  # Parameters of the pipeline
    inputs:
      Env:
        type: choice
        description: 'Environment'
        required: true
        options:
          - T1
          - PRD

jobs:
 #Job name 
  build:
    # Agent pool with specific image
    runs-on: ubuntu-latest

    # Steps
    steps:
      # Check out current repo. (Repo contained in $GITHUB_WORKSPACE)
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.Env }} 