name: Test Pipeline

on:
  # Run the github action manually for the moment.
  workflow_dispatch:

inputs:
  Env:
    description: 'Environment'
    required: true
    default: 'T1'

jobs:
 #Job name 
  build:
    # Agent pool with specific image
    runs-on: ubuntu-latest

    # Steps
    steps:
      # Check out current repo. (Repo contained in $GITHUB_WORKSPACE)
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
