name: Terraform Deploy Infra

run-name: Terraform Deploy Infra on ${{ inputs.Env }}

on:
  push:
    branches:
      - test-terraform
  workflow_dispatch:
    inputs:
      Env:
        type: choice
        description: 'Environment'
        required: true
        options:
          - T1
          - PRD

jobs:
  infra-deploy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.Env }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Test Terraform cli 
        run: terraform version

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init         
      
      - name: Debug
        working-directory: ./terraform
        run: ls -latr ..


      

      # - name: Terraform Plan Validation 
      #   working-directory: ./terraform
      #   run: terraform plan -out=tfplan
      
      # - name: Terraform Plan Show
      #   working-directory: ./terraform
      #   run: terraform show -json tfplan
